version: "3"

services:
  kaspad:
    container_name: kaspad
    image: supertypo/rusty-kaspad:latest
    restart: unless-stopped
    ports:
      - "17110:17110"
    volumes:
      - /var/kaspad:/app/data/
    command: kaspad --yes --utxoindex --rpclisten=0.0.0.0:16110 --rpclisten-borsh=0.0.0.0:17110 --ram-scale=0.3 --nologfiles --disable-upnp

  kaspa_db_filler_db:
    container_name: kaspa_db_filler_db
    image: postgres:16-alpine
    restart: unless-stopped
    shm_size: 1gb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "55543:5432"

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: mthoring@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8989:80"
