version: "3"

services:
  kaspa_explorer:
    container_name: kaspa_explorer
    image: supertypo/kaspa-explorer:latest
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: 2
          memory: 128M
    ports:
      - "8080:8080"
    environment:
      API_URI: http://192.168.168.197:8000
      API_WS_URI: ws://192.168.168.197:8001

  kaspa_db_filler_db:
    container_name: kaspa_db_filler_db
    image: postgres:16-alpine
    restart: unless-stopped
    stop_grace_period: 10m
    shm_size: 1gb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "55543:5432"
    volumes:
      - ./data/:/var/lib/postgresql/data/
