[package]
name = "simply-kaspa-signal"
rust-version.workspace = true
authors.workspace = true
license-file.workspace = true
edition.workspace = true

[lib]
name = "simply_kaspa_signal"
crate-type = ["cdylib", "lib"]

[dependencies]
tokio.workspace = true
log.workspace = true
